# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
#export LANG="en_US.UTF-8"
export TERM="xterm-256color"
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="my-theme"

CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  kubectl
)

source $ZSH/oh-my-zsh.sh

#source "/usr/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh"

# User configuration
#source "/home/ls_brillant/.config/nvim/plugged/gruvbox/gruvbox_256palette.sh"

#local host_name="%{$fg[cyan]%}"
#local path_string="%{$fg[yellow]%}%2c"
#local prompt_string=">"
## Make prompt_string red if the previous command failed.
#local return_status="%(?:%{$fg[blue]%}$prompt_string:%{$fg[red]%}$prompt_string)"
#
#PROMPT="${host_name} ${path_string} ${return_status} %{$reset_color%}"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
unsetopt AUTO_CD

EDITOR=`which nvim` && export EDITOR

alias nv="nvim"

PATH=/usr/local/go/bin:$HOME/go/bin:$HOME/bin:$HOME/.cargo/bin:$PATH && export PATH

escape_slashes() {
    if [[ $# -gt 0 ]]; then
        echo "$@" | sed 's/\//\\\//g'
    else 
        cat | sed 's/\//\\\//g'
    fi
}

view () {
  ft=`file --mime-type "$1" | cut -d: -f2 | sed 's/ //g'`
  case $ft in
      text/*) $EDITOR "$1" ;;
      image/*) feh "$1" ;;
      application/pdf) zathura "$1" ;;
      *) echo "mime-type $ft not supported" ;;
  esac
}

findings () {
    taskell ./findings.md
}

alias clip="xclip -in -selection clipboard"

# Don't show be pycache dir
alias tree="tree -I __pycache__"


source ~/.profile
source ~/.fzf.zsh


autoload -U bashcompinit
bashcompinit

